### ISSUE TITLE
Animated: `useNativeDriver` was not specified. This is a required 'option and must be explicitly set to `true` or `false`

### ISSUE THREAD

**Issue by pankajvaghela** [FullstackStation/react-native-svg-animated-linear-gradient#31]
Allow passing prop for setting this property?

react-native animation [issue](https://github.com/facebook/react-native/issues/28558)

**Comment by bobo717** [comment]
same here

**Comment by virusvn** [comment]
@0.4.0 support: useNativeDriver

**Comment by kathawala** [comment]
Can you put this release on npm?

I've currently pulled in the master branch from github in my project (to avoid the 'useNativeDriver' warning) but I'd like to be able to use a version hosted on npm.

 @virusvn
